spring.application.name=atenciones
server.port=8080

spring.datasource.url=jdbc:oracle:thin:/data/hospital
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=Fullstack-001
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG